-- Create the initial COPR tables for KIDSCLUB
CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS copr_changers (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ddate         timestamp without time zone,
  mgr           varchar(25),
  atm           integer,
  bumper_cars   integer,
  chgr_1        integer,
  chgr_2        integer,
  changer_3     integer,
  changer_4     integer,
  changer_5     integer,
  chgr_7        integer,
  changer_8     integer,
  changer_9     integer,
  changer_12    integer,
  changer_14    integer
);

CREATE TABLE IF NOT EXISTS copr_paidouts (
  id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sales_date timestamp without time zone,
  day        varchar(25),
  mgr        varchar(25),
  department varchar(25),
  type       varchar(25),
  item_name  varchar(25),
  amount     numeric(12,2),
  memo       varchar(50),
  location   varchar(25),
  post_date  timestamp without time zone
);

CREATE TABLE IF NOT EXISTS copr_sales (
  id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sales_date timestamp without time zone,
  day        varchar(25),
  mgr        varchar(25),
  department varchar(25),
  type       text,
  item_name  varchar(25),
  amount     numeric(12,2),
  location   varchar(25),
  post_date  timestamp without time zone
);