-- COPR schema converted from MS Access -> PostgreSQL
-- Mapping notes:
--   Access "Date With Time" -> timestamp without time zone
--   Access "Short Text (n)" -> varchar(n)
--   Access "Long Text" -> text
--   Access "Currency" -> numeric(12,2)
--   ID columns -> integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (allows importing existing IDs)

-- Table: copr_changers
CREATE TABLE IF NOT EXISTS db_schema_copr_copr_changers (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Access ID (Long Integer)
  ddate         timestamp without time zone,                            -- Access: Date With Time
  mgr           varchar(25),                                           -- Short Text (25)
  atm           integer,                                                -- Long Integer
  bumper_cars   integer,
  chgr_1        integer,
  chgr_2        integer,
  changer_3     integer,
  changer_4     integer,
  changer_5     integer,
  chgr_7        integer,
  changer_8     integer,
  changer_9     integer,
  changer_12    integer,
  changer_14    integer
);

-- Table: copr_paidouts
CREATE TABLE IF NOT EXISTS db_schema_copr_copr_paidouts (
  id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Access ID
  sales_date timestamp without time zone,                         -- Date With Time
  day        varchar(25),
  mgr        varchar(25),
  department varchar(25),
  type       varchar(25),
  item_name  varchar(25),
  amount     numeric(12,2),
  memo       varchar(50),
  location   varchar(25),
  post_date  timestamp without time zone
);

-- Table: copr_sales
CREATE TABLE IF NOT EXISTS db_schema_copr_copr_sales (
  id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Access PrimaryKey
  sales_date timestamp without time zone,
  day        varchar(25),
  mgr        varchar(25),
  department varchar(25),
  type       text,              -- Access: Long Text mapped to TEXT
  item_name  varchar(25),
  amount     numeric(12,2),
  location   varchar(25),
  post_date  timestamp without time zone
);

-- Note: I prefixed table names with db_schema_copr_ to avoid accidental collisions; if you prefer plain names (copr_changers, copr_paidouts, copr_sales) I can update.

-- Example: add any additional indexes later based on query patterns, e.g.:
-- CREATE INDEX idx_copr_sales_mgr ON db_schema_copr_copr_sales(mgr);
